from pymongo import MongoClient
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import MongoDBAtlasVectorSearch
from langchain_community.document_loaders import DirectoryLoader
from langchain_openai import OpenAI
from langchain.chains import RetrievalQA
import gradio as gr
from gradio.themes.base import Base
import key_param
from langchain.chat_models import ChatOpenAI

client = MongoClient(key_param.MONGO_URI)
dbName = "PKU"
collectionName = "collection_of_pku_text_blobs"
collection = client[dbName][collectionName]

embeddings = OpenAIEmbeddings(openai_api_key=key_param.openai_api_key, disallowed_special=())

vectorStore = MongoDBAtlasVectorSearch(collection=collection, embedding=embeddings, index_name='knn')

def query_data(query):
    docs = vectorStore.similarity_search(query, k=1)
    as_output = docs[0].page_content

    llm = ChatOpenAI(model_name="gpt-3.5-turbo-16k", openai_api_key=key_param.openai_api_key, temperature=0)
    retriever = vectorStore.as_retriever()
    qa = RetrievalQA.from_chain_type(llm, chain_type="stuff", retriever=retriever)
    retriever_output = qa.run(query)

    return as_output, retriever_output

with gr.Blocks(theme=Base(), title="Q&A PKU") as demo:
    gr.Markdown(
        """
        # Question Answering App using Atlas Vector Search + RAG Architecture
        """
    )
    textbox = gr.Textbox(label="Enter your Question:")
    with gr.Row():
        button = gr.Button("Submit", variant="primary")
    with gr.Column():
        output1 = gr.Textbox(lines=1, max_lines=10, label="Input with just Atlas Vector Search")
        output2 = gr.Textbox(lines=1, max_lines=10, label="Output generated by chaining Atlas Vector Search")

        button.click(query_data, textbox, outputs=[output1, output2])

demo.launch()

# Questions:
# Can you describe PKU?
# What are the clinical features of PKU?
# Is PKU a cause of cataracts?
# Who presented evidence of heterogeneity in PKU?
# Where has brain calcification for PKU been reported?
# Has anyone studied a cohort of women with PKU and if so what was found?